spring:
  datasource:
#    url: ${DATABASE_CONFIG:jdbc:mysql://localhost:3306/db}
#    driverClassName: ${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
#    username: ${DATABASE_USERNAME:root}
#    password: ${DATABASE_PASSWORD:root}
    url: ${DATABASE_CONFIG:jdbc:h2:~/demo-test;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:sa}
    tomcat:
      test-while-idle: true 
      validation-query: SELECT 1
    hikari:
      maximum-pool-size: ${DATABASE_POOL_SIZE:10}
      minimum-idle: 2
      idle-timeout: 60000      
  devtools:
    restart:
      enabled: true
  jpa: 
#    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.MySQL8Dialect}
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    show-sql: ${SHOW_SQL:true}
    open-in-view: true
    hibernate:
      ddl-auto: update
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization: 
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
  main.lazy-initialization: true
  messages:
    basename: i18n/messages,i18n/labels
    encoding: ISO-8859-1
  mvc.format:
    date: iso
    date-time: iso
    time: iso
  mvc.pathmatch.matching-strategy: ant-path-matcher
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  sql:
    init:
      continue-on-error: true
  
server: 
  port: ${SERVER_PORT:8081}

springdoc.swagger-ui.path: /swagger-ui
